language: php

php:
  - 5.3

env:
  - DB=mysql CAKEPHP=2.1.5
  - DB=mysql CAKEPHP=2.2.7
  - DB=mysql CAKEPHP=2.3.6

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - wget https://github.com/cakephp/cakephp/tarball/$CAKEPHP -O cake.tar.gz
  - tar xf cake.tar.gz
  - mv cakephp-cakephp-* ./cakephp
  - chmod -R 777 ./cakephp/app/tmp
  - echo "<?php
    App::build(array(
    'Plugin' => array('/home/travis/build/k1LoW/'),
    ));
    CakePlugin::loadAll();
    " > cakephp/app/Config/bootstrap.php
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    }" > cakephp/app/Config/database.php
  - echo "<?php \$recipe = array('TCPDF', 'FPDI');" > cakephp/r.php
  - cd ./cakephp
  - wget https://raw.github.com/k1LoW/recipe/master/recipe.php --no-check-certificate -O recipe.php && php recipe.php -r r.php
  - chmod 777 app/Vendor/TCPDF/fonts

script:
  - ./lib/Cake/Console/cake test Pdf Lib/Pdf --stderr